#####################
# Simulation Params #
#####################

initialPosition:
  x: 0
  y: 0
  psi: -1.57


##################
# Map Parameters #
##################

positionReference:
  latRef: 26.05553
  lonRef: -80.113299783