#####################
# Simulation Params #
#####################

initialPosition:
  x: 0
  y: 0
  psi: 0

##################
# Map Parameters #
##################

positionReference:
  latRef: 29.152368
  lonRef: -81.017156
