#####################
# Simulation Params #
#####################

initialPosition:
  x: 0
  y: 0
  psi: 0

##################
# Map Parameters #
##################

positionReference:
  latRef: 26.0555
  lonRef: -80.1133
